version: 0.0
os: linux
files:
  - source: /
    destination: /aws-elastic-beanstalk-express-js-sample
file_exists_behavior: OVERWRITE
BeforeInstall:
  - location: /before_script.sh
    timeout: 300
    runas: root
ApplicationStop:
  - location: /after_script.sh
    timeout: 300
    runas: root
